name: "Update pre-commit config versions"
description: "Run pre-commit autoupdate to update pre-commit config versions"

inputs:
  GITHUB_TOKEN:
    description: "Muilti-line list of secrets to expose to the build"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2

    - name: Install stable version of gh cli
      uses: sersoft-gmbh/setup-gh-cli-action@v2
      with:
        version: stable

    - name: Install pre-commit and run autoupdate
      shell: bash
      run: |
        pip install pre-commit
        pre-commit autoupdate

    - name: Create PR with gh cli
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      run: |
        utc_datetime=$(date +'%Y%m%d-%H%M%S')
        sgt_datetime=$(date -d "${utc_datetime} UTC" +"%Y%m%d-%H%M%S" --date='+8 hours')
        git config --global user.email "<>"
        git config --global user.name "GitHub Actions Bot"
        git pull
        git checkout -b update/pre-commit-hooks-${sgt_datetime}
        git add .
        git commit -m "chore: update pre-commit hooks"
        git push origin update/pre-commit-hooks-${sgt_datetime}
        gh pr create --base "main" \
        --title "Test" \
        --body "sample pr trigger" \ 

        

    # - uses: peter-evans/create-pull-request@v5
    #   with:
    #     token: ${{ inputs.GITHUB_TOKEN }}
    #     branch: update/pre-commit-hooks
    #     title: Update pre-commit hooks
    #     commit-message: "chore: update pre-commit hooks"
    #     body: Update versions of pre-commit hooks to latest version.
