name: "Update pre-commit config versions"
description: "Run pre-commit autoupdate to update pre-commit config versions"

inputs:
  GITHUB_TOKEN:
    description: "Muilti-line list of secrets to expose to the build"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2

    - name: Install stable version of gh cli
      uses: sersoft-gmbh/setup-gh-cli-action@v2
      with:
        version: stable

    - name: Install pre-commit and run autoupdate
      shell: bash
      run: |
        pip install pre-commit
        pre-commit autoupdate

    - name: Create PR with gh cli
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      run: |
        git checkout -b update/pre-commit-hooks
        git add .
        git commit -m "chore: update pre-commit hooks"
        gh pr create -f

    # - uses: peter-evans/create-pull-request@v5
    #   with:
    #     token: ${{ inputs.GITHUB_TOKEN }}
    #     branch: update/pre-commit-hooks
    #     title: Update pre-commit hooks
    #     commit-message: "chore: update pre-commit hooks"
    #     body: Update versions of pre-commit hooks to latest version.
