name: "Update pre-commit config versions"
description: "Run pre-commit autoupdate to update pre-commit config versions"

inputs:
  GITHUB_TOKEN:
    description: "Milti-line list of secrets to expose to the build"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2

    - name: Install pre-commit and run autoupdate
      shell: bash
      run: |
        pip install pre-commit
        pre-commit autoupdate

    - uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ inputs.GITHUB_TOKEN }}
        branch: update/pre-commit-hooks
        title: Update pre-commit hooks
        commit-message: "chore: update pre-commit hooks"
        body: Update versions of pre-commit hooks to latest version.
